language: c
compiler: gcc
services:
  - docker

env:
  NGHTTP2_VERSION=1.37.0
  CURL_VERSION=7.64.1
  PREFIX_DIR=/usr/local
# pwd=/home/travis/build/maru/libmicrohttpd-http2

before_install:
  - docker pull marub/libmicrohttpd-http2
script:
  - docker run --rm -it -v $(pwd):/tmp/mhd2 marub/libmicrohttpd-http2
